### ISSUE TITLE
google cloab link for example prediction

### ISSUE THREAD

**Issue by monuminu** [google-research/tapas#1]
Hi Team,

This is an amazing job . Any google colab link to try out some some example quickly . 

Thanks

**Comment by muelletm** [comment]
Thanks for filing this issues. We don't have a colab yet but I'll see if we can put something together!

**Comment by monuminu** [comment]
Thanks .

**Comment by eisenjulian** [comment]
We just updated the code with a colab, you'll find more info in the readme. Thanks for the suggestion!
