### ISSUE TITLE
Pretraining data for intermediate pre-training

### ISSUE THREAD

**Issue by xiang-deng** [google-research/tapas#100]
Hi, i see that the pretraining data for the original TAPAS paper is already released. Is there a plan to release the pretraining data used in the "Understanding tables with intermediate pre-training" paper? Thanks.

**Comment by leezythu** [comment]
The same question here.

**Comment by eisenjulian** [comment]
Hey there, you can find the instructions to regenerate the intermediate pre-training data in the README https://github.com/google-research/tapas/blob/master/INTERMEDIATE_PRETRAIN_DATA.md#code-release

Let us know if you have any questions or run into any problems.
