### ISSUE TITLE
Train model with custom data 

### ISSUE THREAD

**Issue by sparshbhawsar** [google-research/tapas#11]
Hello there,

I tried this model with SQA_large checkpoints and fine tune the model with SQA after this  I want to train the model with my own custom data. I am curious to know how do I pass my own training data into it. After exploring issue #7 solution I found that first the dataset is converted into tsv file then from tsv to interaction, interaction to tf examples then from tf examples to tf records. I didn't found the solution for converting interaction to tf examples containing training data. Do I need to create my own conversion code or is there any predefined way to do this? Any suggestions? It will be more helpful if you update the colab file with conversion code for dealing custom data. 

Thanks 
Sparsh Bhawsar

**Comment by pawelknow** [comment]
Hi,

There is a function "_create_examples" which converts interaction protos to TF examples:
https://github.com/google-research/tapas/blob/a46b7902866f39eca94e49d9b0f71a5e20ee6c1f/tapas/run_task_main.py#L193

It is called by run_task_main with --mode="create_data" [(here](https://github.com/google-research/tapas/blob/a46b7902866f39eca94e49d9b0f71a5e20ee6c1f/tapas/run_task_main.py#L155)) but that also runs the TSV -> interaction which I'm guessing you don't want. The easiest way might be to just import that function and run it from a notebook or a python script:

```python
from tapas import run_task_main

run_task_main._create_examples(
  interaction_dir=INPUT_INTERACTION_DIR,
  example_dir=OUTPUT_EXAMPLE_DIR,
  vocab_file=VOCAB_FILE,
  filename="train",
  batch_size=None,
  test_mode=False)
run_task_main._create_examples(
  interaction_dir=INPUT_INTERACTION_DIR,
  example_dir=OUTPUT_EXAMPLE_DIR,
  vocab_file=VOCAB_FILE,
  filename="dev",
  batch_size=EVAL_BATCH_SIZE,
  test_mode=False)
run_task_main._create_examples(
  interaction_dir=INPUT_INTERACTION_DIR,
  example_dir=OUTPUT_EXAMPLE_DIR,
  vocab_file=VOCAB_FILE,
  filename="eval",
  batch_size=EVAL_BATCH_SIZE,
  test_mode=False)
```

This needs the interactions to be in a TFRecords files "${INPUT_INTERACTION_DIR}/train", "${INPUT_INTERACTION_DIR}/dev" and "${INPUT_INTERACTION_DIR}/eval" and outputs TF examples to "${OUTPUT_EXAMPLE_DIR}".

**Comment by sparshbhawsar** [comment]
I tried this code 
I tried this code ! python tapas/run_task_main.py \
   --task="SQA" \
   --input_dir="${training_data_dir}" \
   --output_dir="${output_dir}" \
   --bert_vocab_file="${tapas_data_dir}/vocab.txt" \
   --mode="create_data"

**Comment by sparshbhawsar** [comment]
I tried this code :

**Comment by sparshbhawsar** [comment]
**TSV file format :**

```
> nt-1	1   1	Give me value of last date?	table_csv/205_100.csv	['(1052, 1)']   ['1.27E-05']
> nt-1	1   2	Give me value of first date?    table_csv/205_100.csv   ['(0, 1)']   [ '-0.01']
> nt-1  1   3   Show the value of 1/8/2019?     table_csv/205_100.csv   ['(89, 1)', '(90, 1)']  ['-621269.14', '244151.77']
> nt-1  2   0   Show value of 2/8/2019?         table_csv/205_100.csv   ['(93, 1)', '(94, 1)', '(95, 1)'] ['-4330359.93', '-629355.21', '261021.99']
```

**Comment by muelletm** [comment]
Great to hear! Thanks!

**Comment by ayushidalmia** [comment]
Hi, The questions in SQA are not tagged with None (when answers are directly from the table) or when they aren't. How is it distinguished?

**Comment by amanknoldus** [comment]
> 

Can you please tell me exact way of passing the answer coordinates, because I am also facing the same issue.
