### ISSUE TITLE
Release of Table Retrieval and Open-domain QA models

### ISSUE THREAD

**Issue by agupta74** [google-research/tapas#112]
Great work on Table Retrieval and Open-domain QA models! Looking forward to their release. Any rough dates on when these models will be released?

**Comment by eisenjulian** [comment]
Hi @agupta74 thanks a lot for the interest, I estimate around two weeks. We will notify you here when it's released

**Comment by agupta74** [comment]
Any update on this?

**Comment by eisenjulian** [comment]
Hi there, sorry for the delay, we have released the models and the code [here](https://github.com/google-research/tapas/blob/master/DENSE_TABLE_RETRIEVER.md). We are also working on more releases with the post-processed dataset derived from NQ and a colab to showcase the end to end system.
