### ISSUE TITLE
Com-positional questions

### ISSUE THREAD

**Issue by AhmedMasryKU** [google-research/tapas#115]
Do you know how we can utilize the TAPAS model to answer compositional questions? 
It seems that currently the model can only apply specific operations which can answer simple questions like "What is the sum of A and B?"

But can we also utilize it to answer questions which require multiple nested operations like "What is the difference between the sum of A and B and the average of C and D?"

Thanks in advance!

**Comment by SyrineKrichene** [comment]
Hi Ahmed,

The current TAPAS models do not handle nested operations.

Here is a brief description of the TAPAS outputs:
- TAPAS output one prediction through the [CLS] token (beginning of
the input sequence) to predict the operation to use or no operation.
- Over the table's tokens the model outputs the probability of the token to
answer the question. A threshold is used to select the relevant tokens.
- In case the model predicts an operation to use, such as the sum, the
model sums over the selected tokens.

Thus TAPAS can apply one operation over multiple selected tokens but does
not cover nested operations use cases.
