### ISSUE TITLE
It's not returning answer for my data

### ISSUE THREAD

**Issue by vitallalaji** [google-research/tapas#12]
Hi,
I'm using tapas on open source data sets.when I tried with only fraction of data i.e. small data(200 to 300 rows) it's returning answer for queries but if the data is big(4000 rows) it's not returning answer but it's able to return table. It's prompting "can't convert too many rows and sometimes sequence too long".  How can I resolve this issue ? I want to try on big data sets. will it work ?
Note : my system is not configured with GPU support and cuda. And I'm performing SQA task.

**Comment by mdmustafizurrahman** [comment]
How long does it take to run the prediction in your machine without GPU? What is your test bacth size? I am also running in laptop the prediction using SQA, and it has been running almost like 50 minutes but still no prediction results.

**Comment by vitallalaji** [comment]
> How long does it take to run the prediction in your machine without GPU? What is your test bacth size? I am also running in laptop the prediction using SQA, and it has been running almost like 50 minutes but still no prediction results.

It's taking around 10 minutes to give the results because I think my RAM is 24 gb..and at a time I'm passing 3 to 4 queries

**Comment by vitallalaji** [comment]
> How long does it take to run the prediction in your machine without GPU? What is your test bacth size? I am also running in laptop the prediction using SQA, and it has been running almost like 50 minutes but still no prediction results.

Its taking around 10 minutes to give the results because of my RAM (24 gb)..and my length of the queries is 3

**Comment by muelletm** [comment]
The problem of long sequences is addressed in #14. Does that help?
