### ISSUE TITLE
SQA Prediction is not producing output test_sequence.tsv

### ISSUE THREAD

**Issue by rajarajac** [google-research/tapas#122]
Seeing below error message:

Traceback (most recent call last):
  File "tapas/tapas/run_task_main.py", line 32, in <module>
    from tapas.retrieval import e2e_eval_utils
ModuleNotFoundError: No module named 'tapas.retrieval'

**Comment by rajarajac** [comment]
changing the python version from 3.6 to 3.7 resolved the issue.

**Comment by Satwikram** [comment]
> changing the python version from 3.6 to 3.7 resolved the issue.

3.7 also it is showing the same error.

**Comment by ManasiPat** [comment]
Hello I tried changing the python version however it still gives me the same error.
