### ISSUE TITLE
Running on CPU only tensorflow

### ISSUE THREAD

**Issue by mdmustafizurrahman** [google-research/tapas#13]
I cannot run the code in my laptop. Can I run this using only CPU?

**Comment by eisenjulian** [comment]
Yes, but depending on your RAM you might want to decrease the batch size by quite a bit. Are you getting an OOM error? Can you get the available RAM on your system?

**Comment by mdmustafizurrahman** [comment]
No, Actuality I installed tensorflow-gpu~=1.14.0 from your requirement file without noticing that initially. Now I have uninstalled that. And installing only tensorflow. Lets see how it goes.

**Comment by mdmustafizurrahman** [comment]
I installed tensoflow 2.0.0 and the previous DLL error is gone. But it is syaing ModuleNotFoundError: No module named 'tensorflow.contrib' 
I guess I have to install tensorflow==1.14.0 same as the gpu version that you have specified in the requirement.txt, right?

**Comment by mdmustafizurrahman** [comment]
currently for prediction you set the test --test_batch_size={len(queries)}. What should be a small batch value to run using only the pretrained model?

**Comment by vitallalaji** [comment]
Hi, I have issues with tensorflow==2.2.0.(not able to import) For my laptop tensorflow==2.0.0 is supporting..does this your new updated script supports tf 2.0 ? If it's support what version do I need install tf-models-officials,tf-proabability,tf-slim, and apache beam ?

**Comment by muelletm** [comment]
We honestly don't now if 2.0 will work. Internally we use 2.2 which is the latest stable release.

You could just try if it works with the versions in the requirements file.

Did you try installing 2.2 with pip in a venv?

Something like that:

```
python3 -m venv env
source env/bin/activate
pip install -e .
```
