### ISSUE TITLE
released nq data is not accessible

### ISSUE THREAD

**Issue by apurvak** [google-research/tapas#147]
I am unable to access this location: `gs://tapas_models/2021_07_22/nq_tables/*`
```gsutil -m cp -R gs://tapas_models/2021_07_22/nq_tables/* .              

zsh: no matches found: gs://tapas_models/2021_07_22/nq_tables/*
```

**Comment by apurvak** [comment]
Closing as this was error on my side.

**Comment by eisenjulian** [comment]
Thanks for the question, the files are there and are public, but it seems that you need the exact path in order to copy them: can you try the following and report back?

```
for file in tables/tables.tfrecord interactions/dev.tfrecord interactions/train.tfrecord interactions/test.tfrecord; do
  gsutil -m cp -R "gs://tapas_models/2021_07_22/nq_tables/${file}" "${nq_data_dir}/${file}"
done
```

**Comment by yashgupta-7** [comment]
Hey! Thanks for this repository.
It says "invalid_grant: Account has been deleted" when we try to access this folder. Can you provide the dataset any other way?
