### ISSUE TITLE
 ValueError: Unknown task: HYBRIDQA

### ISSUE THREAD

**Issue by leezythu** [google-research/tapas#150]
When I tried to fine-tune on HYBRIDQA task, the function 'get_train_filename' in task_utils.py raised this error.
Is it normal?  Or you haven't implemented fine-tuning HYBRIDQA fully.

**Comment by leezythu** [comment]
If not, will you release the code for HYBRIDQA ?

**Comment by eisenjulian** [comment]
Hello @leezythu thanks for your question, I just updated the code with the missing changes. Let me know if you run into any other problems, please consider than unlike other datasets, HybridQA requires training both cell selection model (with task name HYBRIDQA) and a reader model (with task name HYBRIDQA_RC)

**Comment by leezythu** [comment]
@eisenjulian Thanks for your kind response, and it helps me a lot! Now I have gotten tfrecord files for HYBRIDQA, but I run into another problem. I find that the function '_train_and_predict' and '_predict' in run_task_main.py don't include codes for HYBRIDQA. So which file do I need to run to train HYBRIDQA model and HYBRIDQA_RC model? Is it tapas_classifier_experiment.py?
I would appreciate it if you could explain it.

**Comment by eisenjulian** [comment]
You're correct, I've updated those functions to consider HYBRIDQA and HYBRIDQA_RC the datasets as well
