### ISSUE TITLE
Integration with RDBMS

### ISSUE THREAD

**Issue by ChayanBansal** [google-research/tapas#18]
Is there any way to integrate the model with an RDBMS instead of giving the table input each time for prediction?

**Comment by muelletm** [comment]
No, I am afraid, there is not such integration.
Currently the table needs to be encoded from scratch for every question.
We also only support a single table at this point.

**Comment by shashankMadan-designEsthetics** [comment]
Hi @muelletm , any references (research papers/algos) on multiple-table support?
