### ISSUE TITLE
Weird results when running custom question on Colab example

### ISSUE THREAD

**Issue by eliwilner** [google-research/tapas#21]
Hello Again,
I tried to create a simple question: "what is the average Points?" from the example table you published on the Colab notebook.
I got the Column 'Points' just printed out. I tried both base and large models and the results didn't change.

Any thoughts?

**Comment by eisenjulian** [comment]
The SQA model used in the example is not trained with the options to do aggregations, because the dataset only uses answers within the table, you would have to used a model trained on WikiTableQuestions instead, for example.

**Comment by mdmustafizurrahman** [comment]
Can you share the model trained on WikiTableQuestion. please? Because I tried all base models that you shared and got error like this tensorflow.python.framework.errors_impl.NotFoundError: Key column_output_bias not found in checkpoint

**Comment by sbhttchryy** [comment]
Hello, could you please make the pretrained checkpoint available for WikiTQ? Thank you very much.
