### ISSUE TITLE
Smaller TAPAS using Smaller BERT

### ISSUE THREAD

**Issue by mdmustafizurrahman** [google-research/tapas#28]
Your released pre-trained checkpoints of TAPAS are based on BERT base and BERT large. 

Can you release pretrained checkpoints of TAPAS based on some smaller BERT like tiny BERT or Small BERT or Medium BERT as released here https://github.com/google-research/bert

**Comment by eisenjulian** [comment]
Thanks for your interest. Sadly this is not in our immediate plans at this time, but contributions are welcome. Also if there's more interest in this direction we can consider it again in the future.
