### ISSUE TITLE
About batch size

### ISSUE THREAD

**Issue by wenhuchen** [google-research/tapas#3]
Hi there, I try to run your code on wikitable questions on GPU, but the default batch size 512 is way too large. I decrease it to 8 to fit in my RTX card (24 GB), is there anything that I missed? Why is your default batch size so large?

**Comment by muelletm** [comment]
The default hyper-parameters are the ones we used in the paper and we found that bigger (train) batch sizes yield better results. 512 was basically the biggest batch size we could run.

Decreasing the batch size will probably lead to worse performance.

You basically have two options: 

- train on TPUs
- experiment with the `gradient_accumulation_steps` option discussed in the README (it should allow you to split a logical batch into a number of actual batches).
