### ISSUE TITLE
Script to convert Wikipedia article infobox to required tabular format

### ISSUE THREAD

**Issue by GaurangTandon** [google-research/tapas#34]
Hi, in the Colab notebook, I noticed the table has to be in a specific format (using pipes for columns) for the prediction to work. Also, in [pre-training](https://github.com/google-research/tapas/blob/master/PRETRAIN_DATA.md), it is mentioned that tables were extracted from Wikipedia into the "proto text format". 

I looked into the code and could not find any scripts that: (1) given Wikipedia page url, scrape the corresponding infobox to produce a table, and (2) produce that table in the piped format which is in the colab notebook.

Initially I was planning to write my own scraper for Wikipedia infobox, but it would be really time consuming, especially if you have a script already for it, then that would be great. Thanks!

**Comment by GaurangTandon** [comment]
Also, how do I replicate the pre-training output in the colab notebook? I modified the last cell to be  this:

```
result = predict("""
Born                                                         | Died	                                              | Cause of death | Resting place	              | Occupation	 | Spouse(s)	      | Children	       | Relatives	                  | Awards
Elvis Aron Presley January 8, 1935 Tupelo, Mississippi, U.S. | August 16, 1977 (aged 42) Memphis, Tennessee, U.S. | Heart attack   | Graceland Memphis, Tennessee | Singer actor | Priscilla Beaulieu | Lisa Marie Presley | Riley Keough (granddaughter) | Presidential Medal of Freedom (posthumous, 2018)
""", ["DESCRIPTION", "TITLE", "SEGMENT_TITLE"])
```

However I obviously don't get expected output.


```
is_built_with_cuda: True
is_gpu_available: True
GPUs: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
Training or predicting ...
Evaluation finished after training step 0.
Born | Died | Cause of death | Resting place | Occupation | Spouse(s) | Children | Relatives | Awards
-- | -- | -- | -- | -- | -- | -- | -- | --
Elvis Aron Presley January 8, 1935 Tupelo, Mississippi, U.S. | August 16, 1977 (aged 42) Memphis, Tennessee, U.S. | Heart attack | Graceland Memphis, Tennessee | Singer actor | Priscilla Beaulieu | Lisa Marie Presley | Riley Keough (granddaughter) | Presidential Medal of Freedom (posthumous, 2018)
> DESCRIPTION
Elvis Aron Presley January 8, 1935 Tupelo, Mississippi, U.S.
> TITLE
Elvis Aron Presley January 8, 1935 Tupelo, Mississippi, U.S.
> SEGMENT_TITLE
Elvis Aron Presley January 8, 1935 Tupelo, Mississippi, U.S.
```

I wished to get output similar to what is given in the `original_text` field of the corresponding queries on the [pre-training page](https://github.com/google-research/tapas/blob/master/PRETRAIN_DATA.md).

**Comment by muelletm** [comment]
So the pipe-based format is just used in the colab to allow easy creation of table examples.

The "text proto format" is decribed here:

https://github.com/google-research/tapas/blob/master/PRETRAIN_DATA.md

We also link to a dataset that contains the Wikipedia data we used for pre-training in that format.

We didn't open source the code that was used to convert from Wikipedia HTML to that format.

If you want to implement that I would recommend using something like pandas.read_html:

https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.read_html.html
