### ISSUE TITLE
[bug] tapas_pretraining_experiment.py  missing Flag "model_dir" parameter

### ISSUE THREAD

**Issue by mdmustafizurrahman** [google-research/tapas#40]
model_dir flag is missing in the tapas_pretraining_experiment.py I have added the flag in the file. Please update the file accordingly, 

python tapas/experiments/tapas_pretraining_experiment.py \
  --eval_batch_size=32 \
  --train_batch_size=512 \
  --tpu_iterations_per_loop=5000 \
  --num_eval_steps=100 \
  --save_checkpoints_steps=600 \
  --num_train_examples=512000000 \
  --max_seq_length=128 \
  --input_file_train="/data/t-mdra/data/tapas_pretrainig_data/train.tfrecord" \
  --input_file_eval="/data/t-mdra/data/tapas_pretrainig_data/test.tfrecord" \
  --init_checkpoint="/data/t-mdra/projects/tapas/bert_checkpoints/L-6_H-256/model.ckpt" \
  --bert_config_file="/data/t-mdra/projects/tapas/bert_checkpoints/L-6_H-256/bert_config.json" \
  --model_dir="/data/t-mdra/projects/tapas/tapas/pretrained_model/" \
  --do_train

**Comment by thomasmueller-google** [comment]
Thinks for reporting this. I'll have a look.

**Comment by thomasmueller-google** [comment]
Should be fixed now.
