### ISSUE TITLE
WTQ fine-tune

### ISSUE THREAD

**Issue by lairikeqiA** [google-research/tapas#42]
I plan to fine-tune WTQ on pre-trained SQA model. How do I create the correct format of WTQ?

**Comment by thomasmueller-google** [comment]
Hi!

This should be explained in the README, basically the following command should create the data in interaction and TF example format:

```
python3 tapas/run_task_main.py \
  --task="WTQ" \
  --input_dir="${wtq_data_dir}" \
  --output_dir="${output_dir}" \
  --bert_vocab_file="${tapas_data_dir}/vocab.txt" \
  --mode="create_data"
```
