### ISSUE TITLE
WTQ prediction

### ISSUE THREAD

**Issue by lairikeqiA** [google-research/tapas#43]
I plan to predict WTQ. How can I set parameters when I run convert_prediction.py?

**Comment by lairikeqiA** [comment]
flags.DEFINE_list('interaction_files', None,
                  'A list of files contain interactions protos.')
flags.DEFINE_list('prediction_files', None,
                  'A list of files that contain model prediction.')
flags.DEFINE_string('output_directory', None,
                    'Output directory where converted files will be stored.')
flags.DEFINE_enum_class('dataset_format', None,
                        convert_predictions_utils.DatasetFormat,
                        'Dataset format.')

**Comment by thomasmueller-google** [comment]
interactions are the interaction you create from the original WTQ data.
run_task_main can do that for you.
The Dataset format should be tfrecords.
The predictions are the once created by run_task_main.
