### ISSUE TITLE
Where we can download WIKISQL pre-trained tapas model?

### ISSUE THREAD

**Issue by monk1337** [google-research/tapas#45]
First of all, thank you for this awesome work and making it open source.

SQA large model is not supporting Logical Form and Aggregation based questions. As shown in the paper WIKISQL model consists of both  Logical Form and Aggregation. 

From where we can download WIKISQL checkpoint of the trained model?

- Aaditya

**Comment by thomasmueller-google** [comment]
So far we didn't have model trained on WIKISQL but we released one today.

I would recommend using the WTQ model, though. Since WIKISQL has some strange biases (e.g. many aggregations are performed over 0 or 1 rows).
