### ISSUE TITLE
Convert the TAPAS predictions to the WTQ format and run the official evaluation script.

### ISSUE THREAD

**Issue by lairikeqiA** [google-research/tapas#47]
When I convert the TAPAS predictions to the WTQ format and run the official evaluation script. The converted result is almost 0%. What's wrong with that? 
python3 /home/cjc/tapas-master/tapas/scripts/convert_predictions.py \
  --interaction_files=/home/cjc/tapas-master/WTQ/wtq/interactions/test.tfrecord \
  --prediction_files=/home/cjc/tapas-master/WTQ/wtq/test.tsv \
  --output_directory=/home/cjc/tapas-master/tapas/experiments \
  --dataset_format=WIKITABLEQUESTIONS
python evaluator.py -t /home/cjc/tapas-master/WTQ/tagged/data /home/cjc/tapas-master/tapas/experiments/test.tsv

If I don't convert the TAPAS predictions to the WTQ format, what is the mean of the result of TAPAS prediction? Your released result 49.52%  on tapas_wtq_wikisql_sqa_masklm_large_resst are converted or not?

**Comment by thomasmueller-google** [comment]
The numbers we report in the README are denotation accuracy without conversion.

**Comment by thomasmueller-google** [comment]
Can share the output of convert_predictions? Looks like there is something wrong. The numbers (internal vs official) are usually pretty close.

**Comment by thomasmueller-google** [comment]
Thanks for sharing the files.

I think you are running on the wrong prediction file.

The file you are using is the intermediate TSV file that we generate during data creation.

A prediction file should look like this:

```
question_id	id	annotator	position	answer_coordinates	gold_aggr	pred_aggrnu-1-0_0	nu-1	0	0	['(1, 0)']	0	1nu-10-0_0	nu-10	0	0	['(12, 0)']	0	0nu-100-0_0	nu-100	0	0	['(6, 0)']	0	0nu-1000-0_0	nu-1000	0	0	['(0, 2)']	0	0nu-1001-0_0	nu-1001	0	0	[]	0	3
```

You will find it in the model directory.
