### ISSUE TITLE
reset_position_index_per_cell options

### ISSUE THREAD

**Issue by lairikeqiA** [google-research/tapas#49]
What is the specific mean of using relative position indices when a new cell starts about reset_position_index_per_cell options?

**Comment by thomasmueller-google** [comment]
To be honest I don't completely understand the question.

So I'll simply explain what `reset_position_index_per_cell` does:

The idea is that usually we use absolute position indices as in normal text Bert.

So a simple table:

A A | B B
--  | --
a a | b b

Will get the following indices:

query | ? | [SEP] | A | A | B  | B | a | a | b | b
------- | -- | ------- | -- | -- | -- | -- | -- | -- | -- | --
0        | 1 | 2        | 3  | 4 | 5 | 6  | 7 | 8  | 9  | 10

When you set  `reset_position_index_per_cell=true`, you will get:

query | ? | [SEP] | A | A | B  | B | a | a | b | b
------- | -- | ------- | -- | -- | -- | -- | -- | -- | -- | --
0        | 1 | 2        | 0  | 1 | 0 | 1  | 0 | 1  | 0  | 1

Which usually performance a bit better and allows you to encode longer sequences without running out of embeddings.

**Comment by eisenjulian** [comment]
Closing for the time being. Please reopen if the answer was not clear.
