### ISSUE TITLE
wtq prediction 

### ISSUE THREAD

**Issue by bpquestion** [google-research/tapas#56]
I would like to make predictions on aggregation questions. Can you please give us the notebook for wtq predictions like you did for sqa or just the command line for the run?
Thanks

**Comment by thomasmueller-google** [comment]
Yes, that should be easy to do. I'll have a look!

**Comment by bpquestion** [comment]
OK! Thanks.

**Comment by thomasmueller-google** [comment]
Added a new colab:

http://tiny.cc/tapas-wtq-colab

**Comment by bpquestion** [comment]
Thanks. Is is possible to have also the notebook for wikisql predictions?

**Comment by thomasmueller-google** [comment]
I don't think it's worth having a separate colab at this point:
* The differences are minimal (you basically just need to change the model and the parameter to the task flag)
* WikiSQL has some weird biases (most aggregation examples only aggregate 0 or 1 row)

I would therefore recommend using the WTQ models, unless you have a very specific use-case in mind?

**Comment by bpquestion** [comment]
Not really. But the accuracy looks better with wikisql models
