### ISSUE TITLE
answers with wtq predictions

### ISSUE THREAD

**Issue by bpquestion** [google-research/tapas#58]
When I run predictions on wtq models with aggregation questions, I do not get the right number. For example, if the answer should be the sum of 10 and 20, the answer obtained is: "SUM of 10,20" and not "30".

**Comment by thomasmueller-google** [comment]
I am assuming you are talking about the new WTQ colab which just is supposed to serve as an example.

The script that we use to get the actual denotations for WTQ is [convert_predictions.py](https://github.com/google-research/tapas/blob/master/tapas/scripts/convert_predictions.py).

The underlying logic is in [execute](https://github.com/google-research/tapas/blob/ab1c7404fce708fa66b742393a310b1da4e39643/tapas/scripts/calc_metrics_utils.py#L238).
