### ISSUE TITLE
How do I put my output of the bert into the tapas?

### ISSUE THREAD

**Issue by lairikeqiA** [google-research/tapas#59]
I plan to use the output of my bert to replace the output of the bert of tapas. Where should I input the output of my bert into tapas?

**Comment by thomasmueller-google** [comment]
I am not entirely following. With some simplification we have:

TAPAS: input  > Bert (with special embeddings) | Answer selection > outputs

I understand you want to replace the BERT model with a custom one but use our answer selection loss?

If your custom BERT model only differs in the parameters you can just load it. You might have to disable the special embeddings (row, column, numeric ranks).

If you have a different Bert implementation you might have to chance some code.
[This](https://github.com/google-research/tapas/blob/master/tapas/models/tapas_classifier_model.py#L926) is where we create the Bert model in the code.

**Comment by eisenjulian** [comment]
Will close this one for the time being, please reopen if there are further questions or clarifications.
