### ISSUE TITLE
TAPAS Performance on custom data

### ISSUE THREAD

**Issue by dipranjan** [google-research/tapas#63]
Hello, 

Thank you for this brilliant project. I have been playing around with the colab file in this github. While the results the great in the example shared, the results are surprisingly inaccurate when doing the same on a custom data frame.
Now there might be 2 reasons for this:
1. I am doing something wrong
2. Because this is a domain specific data it might be that during training the model has never seen this type of data, but given the nature of the questions I thought the pre-trained model might be able to generalize and answer these

# Example custom data
result = predict("""
Year | Quarter | Region | Revenue
2020 | Q1      | APJ    | 12507
2020 | Q2      | APJ    | 125900
2020 | Q3      | APJ    | 125008
2020 | Q4      | APJ    | 19800
2021 | Q1      | APJ    | 1200
2021 | Q2      | APJ    | 12570
2021 | Q3      | APJ    | 1290
2021 | Q4      | APJ    | 120
2020 | Q1      | KYZ    | 920
2020 | Q2      | KYZ    | 9200
2020 | Q3      | KYZ    | 95500
2020 | Q4      | KYZ    | 92500
2021 | Q1      | KYZ    | 82500
2021 | Q2      | KYZ    | 62500
2021 | Q3      | KYZ    | 2500
2021 | Q4      | KYZ    | 125000
""", ["Highest revenue in APJ?","Total Revenue in APJ?"])

The results came as follows:

> Highest revenue in APJ?
12507, 125008
> Total Revenue in APJ?
120, 125008

I was hoping if you guide me as to how best to train/fine-tune the model so that it is able to answer these questions?

Thanks again

**Comment by thomasmueller-google** [comment]
Hi!

In general, it's often hard to tell why a specific example doesn't yield the expected results.
The models here are also provided to facilitate further research they are not really meant to have off-the-shelf quality.

That said, I quickly tried your example in our new WTQ [colab](http://tiny.cc/tapas-wtq-colab) and it does work for me:

```
> Highest revenue in APJ?
SUM of 125900
> Total Revenue in APJ?
SUM of 12507, 125900, 125008, 19800, 1200, 12570, 1290, 120
```

You can see that it predicts a spurious `SUM` for the first question but the answer is still correct.

**Comment by dipranjan** [comment]
Hey,

Thanks for the quick response. I tried in the WTQ Colab notebook it is giving better results than the one which I used last.

Just to give you a context at what we are trying to do, we have built a NLP model which is good at fetching the data and as a last pinpointing exercise we are trying to leverage TAPAS. 

For example if someone says "which quarter has the highest revenue in the last 4 years". Our model is good at understanding this and fetching the 4 years worth of data. As a last pinpointing exercise as to which quarter actually has the highest revenue we want to leverage TAPAS by passing the fetched dataframe to it.

Now this is something which I think TABERT is also attempting but anyways we have the first part of the problem sorted, we are trying to get around with the second part.

Given this problem how would you suggest we best leverage TAPAS?

**Comment by eisenjulian** [comment]
Hi @dipranjan can you clarify whether you will need aggregations in your application, and whether you have some training data, and of what form?

**Comment by dipranjan** [comment]
Hi @eisenjulian, I cannot share or show the actual data due to company policies. But let me give you a similarish example of what we have and what we are trying to do.

Imagine a retail store DB, if some one asks: _"common best selling cosmetic products in the last month vs current month in APJ"_

Now our model can parse this and fetch data - _[top 10] [cosmetic products] [last month, current month] [revenue] [APJ]_
Our training data, NLP model, SQL engine is geared towards this, mostly in deriving the intent of the question along with entities and their roles. A lot more complexities are involved but this is the gist.

Now once the data is fetched it is still just data and currently the user has to derive the information from the data. We were thinking of levearging to TAPAS to answer this last round.

Aggregations will mostly not be needed as any aggregation we can do from our model.

Another question on the same data might be:

_Difference in revenue between top selling cosmetic products in the last month vs current month in APJ_

**Comment by eisenjulian** [comment]
Thanks for the explanation. If aggregation is required you could use a pre-trained WTQ checkpoint of the retrieved data. As @thomasmueller-google pointed out, the level generalization to your domain is hard to predict, so you might consider creating a small internal dataset to evaluate, or even better, to fine-tune the WTQ checkpoint to your use-case. 

In particular, if you have annotations for the specific aggregation (SUM, COUNT, AVG, etc) required, instead of relying on the unsupervised set-up where only the numeric answer is known, then the training will be much faster (more similar to WikiSQL than WTQ).

Another useful step could be to run more pre-training with un-annotated data from your domain, but that would require more hardware and time than just fine-tuning.

**Comment by dipranjan** [comment]
Thanks @eisenjulian for the answer. Will try out these, though I am not very familiar with the fine tuning. Thanks for all the help.

**Comment by muelletm** [comment]
Closing for now, feel free to reopen if there is an update.
