### ISSUE TITLE
One time loading of table during inference

### ISSUE THREAD

**Issue by Akshaysharma29** [google-research/tapas#66]
Hi team, I have tried your colab notebook and found it very useful but I have a question that
- is there a way to load the table only once during inference so that it is not required to send a complete table every time for a prediction.

For example, if I want to query 1 question at a time then I have to pass complete table every time.

**Comment by thomasmueller-google** [comment]
Hi!

Great that you found the colab useful!

It's not possible to use the same table representation for different queries. The BERT-style encoder needs to encode both (table and question) jointly (that is the table token embeddings depend on the question tokens).

**Comment by Akshaysharma29** [comment]
Hi, @thomasmueller-google thanks for the response.
