### ISSUE TITLE
Configuration for training model on WTQ

### ISSUE THREAD

**Issue by sparshbhawsar** [google-research/tapas#71]
Hello, 

I want to know what are the VM configuration required to train model on WTQ.

**Comment by eisenjulian** [comment]
Hello @sparshbhawsar please see the [hardware requirements](https://github.com/google-research/tapas#hardware-requirements) section of the readme. The main need will be on the accelerator side (GPU or TPU). In the official BERT repository that is linked in that section, you will also find examples to run using cloud instances. Hope this helps, and let us know if there are any further questions.
