### ISSUE TITLE
Error when create_data is used on WIKISQL

### ISSUE THREAD

**Issue by aminfardi** [google-research/tapas#72]
I'm trying to replicate the results (to ensure I'm setting everything up properly) using the WikiSQL dataset. I am using "tapas_wikisql_sqa_masklm_small_reset.zip" model.  However when I try running:

```
!python tapas/tapas/run_task_main.py \
  --task="WIKISQL" \
  --input_dir="data/" \
  --output_dir="results/wsql/input_data" \
  --bert_vocab_file="tapas_model/bert_config.json" \
  --mode="create_data"
```

I encounter the following error:

```
I1005 02:55:27.819439 139825599944576 sqa_utils.py:102] Total	Valid	Failed	File
56355	55775	580	train.tsv
8421	8421	0	dev.tsv
15878	15878	0	test.tsv
Creating TF examples ...
I1005 02:55:36.143442 139825599944576 run_task_main.py:152] Creating TF examples ...
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tapas/scripts/prediction_utils.py:48: tf_record_iterator (from tensorflow.python.lib.io.tf_record) is deprecated and will be removed in a future version.
Instructions for updating:
Use eager execution and: 
`tf.data.TFRecordDataset(path)`
W1005 02:55:36.144381 139825599944576 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tapas/scripts/prediction_utils.py:48: tf_record_iterator (from tensorflow.python.lib.io.tf_record) is deprecated and will be removed in a future version.
Instructions for updating:
Use eager execution and: 
`tf.data.TFRecordDataset(path)`
I1005 02:55:36.159258 139825599944576 number_annotation_utils.py:149] Can't consolidate types: (None, text: "Current slogan"
) {0: [float_value: 2013.0
, date {
  year: 2013
}
], 1: [], 2: [], 3: [], 4: [], 5: [], 6: []} 1
Traceback (most recent call last):
  File "tapas/tapas/run_task_main.py", line 782, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "tapas/tapas/run_task_main.py", line 743, in main
    output_dir=output_dir)
  File "tapas/tapas/run_task_main.py", line 178, in _create_all_examples
    test_mode=test_mode)
  File "tapas/tapas/run_task_main.py", line 231, in _create_examples
    examples.append(converter.convert(interaction, i))
  File "/usr/local/lib/python3.6/dist-packages/tapas/utils/tf_example_utils.py", line 1096, in convert
    drop_rows_to_fit=self._drop_rows_to_fit)
  File "/usr/local/lib/python3.6/dist-packages/tapas/utils/tf_example_utils.py", line 1018, in _to_trimmed_features
    serialized_example.tokens, feature_dict, table=table, question=question)
  File "/usr/local/lib/python3.6/dist-packages/tapas/utils/tf_example_utils.py", line 673, in _to_features
    input_ids = self._to_token_ids(tokens)
  File "/usr/local/lib/python3.6/dist-packages/tapas/utils/tf_example_utils.py", line 656, in _to_token_ids
    return self._tokenizer.convert_tokens_to_ids(_get_pieces(tokens))
  File "/usr/local/lib/python3.6/dist-packages/tapas/utils/tf_example_utils.py", line 332, in convert_tokens_to_ids
    return self._wp_tokenizer.convert_tokens_to_ids(word_pieces)
  File "/usr/local/lib/python3.6/dist-packages/official/nlp/bert/tokenization.py", line 190, in convert_tokens_to_ids
    return convert_by_vocab(self.vocab, tokens)
  File "/usr/local/lib/python3.6/dist-packages/official/nlp/bert/tokenization.py", line 150, in convert_by_vocab
    output.append(vocab[item])
KeyError: '[CLS]'
```

Is this an issue with the WikiSQL data itself, or is it the .py utility within TAPAS?

**Comment by alxblandin** [comment]
Not sure if it's the source of error but you seem to have put the _bert_config.json_ file in the _bert_vocab_file_ parameter. Maybe you should put there the _vocab.txt_ file.

**Comment by alxblandin** [comment]
I've also got errors trying the same thing on the WIKISQL_SUPERVISED task:
> I1005 15:18:22.789283 33856 sqa_utils.py:102] Total     Valid   Failed  File
8421    8421    0       dev.tsv
15878   15878   0       test.tsv
56355   56355   0       train.tsv
Creating TF examples ...
I1005 15:18:32.054150 33856 run_task_main.py:152] Creating TF examples ...
Traceback (most recent call last):
  File "tapas/tapas/run_task_main.py", line 782, in <module>
    app.run(main)
  File "C:\Users\alexi\AppData\Roaming\Python\Python37\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "C:\Users\alexi\AppData\Roaming\Python\Python37\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "tapas/tapas/run_task_main.py", line 743, in main
    output_dir=output_dir)
  File "tapas/tapas/run_task_main.py", line 178, in _create_all_examples
    test_mode=test_mode)
  File "tapas/tapas/run_task_main.py", line 220, in _create_examples
    converter = tf_example_utils.ToClassifierTensorflowExample(config)
  File "C:\Users\alexi\AppData\Roaming\Python\Python37\site-packages\tapas\utils\tf_example_utils.py", line 1053, in __init__
    super(ToClassifierTensorflowExample, self).__init__(config)
  File "C:\Users\alexi\AppData\Roaming\Python\Python37\site-packages\tapas\utils\tf_example_utils.py", line 963, in __init__
    super(ToTrimmedTensorflowExample, self).__init__(config)
  File "C:\Users\alexi\AppData\Roaming\Python\Python37\site-packages\tapas\utils\tf_example_utils.py", line 348, in __init__
    self._tokenizer = TapasTokenizer(config.vocab_file)
  File "C:\Users\alexi\AppData\Roaming\Python\Python37\site-packages\tapas\utils\tf_example_utils.py", line 318, in __init__
    vocab_file=vocab_file, do_lower_case=True)
  File "C:\Users\alexi\AppData\Roaming\Python\Python37\site-packages\official\nlp\bert\tokenization.py", line 175, in __init__
    self.vocab = load_vocab(vocab_file)
  File "C:\Users\alexi\AppData\Roaming\Python\Python37\site-packages\official\nlp\bert\tokenization.py", line 137, in load_vocab
    token = convert_to_unicode(reader.readline())
  File "C:\Users\alexi\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\lib\io\file_io.py", line 169, in readline
    self._preread_check()
  File "C:\Users\alexi\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\lib\io\file_io.py", line 79, in _preread_check
    self.__name, 1024 * 512)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. tensorflow.python._pywrap_file_io.BufferedInputStream(arg0: str, arg1: int)

Invoked with: None, 524288

I called the creation of data like this

>     os.system('python tapas/tapas/run_task_main.py '+
        '--task="WIKISQL_SUPERVISED" '+
        '--input_dir="WikiSQL/data" '+
        '--output_dir="results/wikisql_supervised" '+
        '--bert_config_file="tapas_wikisql_sqa_masklm_base_reset/bert_config.json" '+
        '--mode=create_data"')

I got similar erros by the past and it seems to be due to the fact that I'm using the wrong model for fine-tuning task. It is not clear  in the README to figure which model I should use to do it (SQA? MASKLM? wikisql_sqa_masklm?).

**Comment by aminfardi** [comment]
> @aminfardi Not sure if it's the source of error but you seem to have put the _bert_config.json_ file in the _bert_vocab_file_ parameter. Maybe you should put there the _vocab.txt_ file.

Thanks for flagging that. I fixed those parameters and I'm running it again, though seeing lots of errors still. I'll see if it finishes running (going further than it did before, so errors might just be it filtering out tables that are too long etc)

**Comment by aminfardi** [comment]
@alxblandin, curious what your report.tsv says? Mine shows this:

```
# Dataset: dev.tsv supervision_mode: SupervisionMode.NONE
# Dataset: test.tsv supervision_mode: SupervisionMode.NONE
# Dataset: train.tsv supervision_mode: SupervisionMode.REMOVE_ALL

Total	Valid	Failed	File
56355	55775	580	train.tsv
8421	8421	0	dev.tsv
15878	15878	0	test.tsv
# Detailed error statistics for train.tsv:
# failed-Cannot parse answer: [answer_coordinates: Assignment is ambiguous][float_value: Cannot convert to multiple answers to single float]	580
```

This is on the updated call as follows (note I'm not doing supervised):

```
!python tapas/tapas/run_task_main.py \
  --task="WIKISQL" \
  --input_dir="data/" \
  --output_dir="results/wsql/input_data" \
  --bert_config_file="tapas_model/bert_config.json" \
  --bert_vocab_file="tapas_model/vocab.txt" \
  --mode="create_data"
```

**Comment by alxblandin** [comment]
@aminfardi Where/How did you get your data? I followed the step by step Installation in the WikiSQL repo and use the data folder ...and apparently I got no fails (you got 580 fails in the train file).

> Total     Valid   Failed  File
8421    8421    0       dev.tsv
15878   15878   0       test.tsv
56355   56355   0       train.tsv

**Comment by aminfardi** [comment]
@alxblandin, I'm doing this in colab by following the WikiSQL steps like this:

```
! git clone https://github.com/salesforce/WikiSQL
! pip install -r WikiSQL/requirements.txt 
! tar xvjf WikiSQL/data.tar.bz2
```
By the end of it, I have a data/ directory with the train/dev/test .db/.tables.jsonl/.jsonl files. I'm confused about the fails as well.

**Comment by alxblandin** [comment]
@aminfardi Did all the programm failed? Or do you still have all the tf-examples exept the failed ones?

**Comment by aminfardi** [comment]
@alxblandin it just finished the create_data step and it appears that I have tf-examples but not the failed ones. I'm trying predict_evaluate on it. Will report back.

PS. are you doing this on Colab as well? I'm considering Colab Pro to speed things up.

**Comment by alxblandin** [comment]
@aminfardi No I have to do it on local. I had a lot of 'Can't convert interaction: Sequence too long' and "Can't consolidate types" errors. At the end of the fine-tuning I got this 

> Processed: test.tfrecord
I1005 16:57:14.099190 44624 run_task_main.py:152] Processed: test.tfrecord
Num questions processed: 15878
I1005 16:57:14.100188 44624 run_task_main.py:152] Num questions processed: 15878
Num examples: 15243
I1005 16:57:14.110162 44624 run_task_main.py:152] Num examples: 15243
Num conversion errors: 635
I1005 16:57:14.111160 44624 run_task_main.py:152] Num conversion errors: 635
Padded with 21 examples.
I1005 16:57:14.146098 44624 run_task_main.py:152] Padded with 21 examples.

I don't know if it's normal but I'll try predict and evaluate too on what I got.

**Comment by aminfardi** [comment]
@alxblandin yup same, a lot of those errors. Here's my final tally for comparison:

```
Processed: test.tfrecord
I1005 14:03:38.007062 140605349005184 run_task_main.py:152] Processed: test.tfrecord
Num questions processed: 15878
I1005 14:03:38.007266 140605349005184 run_task_main.py:152] Num questions processed: 15878
Num examples: 15243
I1005 14:03:38.007367 140605349005184 run_task_main.py:152] Num examples: 15243
Num conversion errors: 635
I1005 14:03:38.007445 140605349005184 run_task_main.py:152] Num conversion errors: 635
Padded with 21 examples.
I1005 14:03:38.041672 140605349005184 run_task_main.py:152] Padded with 21 examples.
```

Looks like we have identical results after all?

**Comment by alxblandin** [comment]
@aminfardi Yes so your failed attempt may have not impact after all :)

**Comment by aminfardi** [comment]
@alxblandin, any luck with your predict_evaluate? So far a lot of sleeping for me:

```
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 4.0, '_log_step_count_steps': None, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1, '_tpu_config': TPUConfig(iterations_per_loop=1000, num_shards=8, num_cores_per_replica=None, per_host_input_for_training=3, tpu_job_name=None, initial_infeed_sleep_secs=None, input_partition_dims=None, eval_training_input_configuration=2, experimental_host_call_every_n_steps=1), '_cluster': None}
INFO:tensorflow:_TPUContext: eval_on_tpu True
I1005 16:13:07.712592 140186778113920 tpu_context.py:216] _TPUContext: eval_on_tpu True
Sleeping 5 mins before predicting
I1005 16:13:07.713266 140186778113920 run_task_main.py:152] Sleeping 5 mins before predicting
Sleeping 5 mins before predicting
I1005 16:18:07.792725 140186778113920 run_task_main.py:152] Sleeping 5 mins before predicting
Sleeping 5 mins before predicting
I1005 16:23:07.893801 140186778113920 run_task_main.py:152] Sleeping 5 mins before predicting
Sleeping 5 mins before predicting
I1005 16:28:07.994912 140186778113920 run_task_main.py:152] Sleeping 5 mins before predicting

```

**Comment by alxblandin** [comment]
@aminfardi I got the same issue, where have you put the directory exactly?

**Comment by aminfardi** [comment]
@alxblandin the code that I run is (note the mode is evaluate, I still can't get the predict_and_evaluate working):

```
!python tapas/tapas/run_task_main.py \
  --task="WIKISQL" \
  --output_dir="results/wsql/input_data" \
  --bert_config_file="tapas_model/bert_config.json" \
  --bert_vocab_file="tapas_model/vocab.txt" \
  --use_tpu="true" \
  --mode="evaluate"
```

and my model is in:

`results/wsql/input_data/wikisql/model`

Note that once you run it in that mode, it might crash looking for test.tsv file. I just moved the test.tsv file into the model folder as well and that worked.

**Comment by alxblandin** [comment]
@aminfardi So you put the model checkpoint in the model folder? Mine is empty at the begininng of the programm. What are the differences between yout tapas_model/ folder and your input_data/wikisql/model folder?

**Comment by aminfardi** [comment]
> @aminfardi So you put the model checkpoint in the model folder? Mine is empty at the begininng of the programm. What are the differences between yout tapas_model/ folder and your input_data/wikisql/model folder?

They are identical. Once I did the pull into the tapas_model folder, I copied the whole thing over to the input_data/wikisql/model folder. I just didn’t change the BERT links because they were still technically valid. I’m not sure why I couldn’t do the same directory path with the model but this worked.

**Comment by alxblandin** [comment]
> > @aminfardi So you put the model checkpoint in the model folder? Mine is empty at the begininng of the programm. What are the differences between yout tapas_model/ folder and your input_data/wikisql/model folder?
> 
> @alxblandin They are identical. Once I did the pull into the tapas_model folder, I copied the whole thing over to the input_data/wikisql/model folder. I just didn’t change the BERT links because they were still technically valid. I’m not sure why I couldn’t do the same directory path with the model but this worked.

And what are your results? Do you retrieve the same as in the repo?

UPDATE : It worked ! :D get  denotation accuracy : 0.908742 (which is...higher than expected???)

**Comment by aminfardi** [comment]
@alxblandin I get the exact same accuracy as you. Are you doing it on supervised still? Or is this just WIKISQL (ie my code exactly)? 

I was a little concerned about the high score as wel.

**Comment by alxblandin** [comment]
@aminfardi No I keept it supervised which is a concern as well. We do not use the exact same model either (I use the base one, you use the small version). 
The results may be due to the default parameters keeping the same values. If we can make the predict_evaluate task I think we will start to see some differencies.

**Comment by aminfardi** [comment]
@alxblandin yes agreed, I’ll get back at it in a bit here. Please ping me if you manage to crack the nut!

**Comment by aminfardi** [comment]
@alxblandin I'm close, but my Colab just nuked my session so I wanted to share my progress before signing off for the night. The key is to create a checkpoint in the model/ folder. They do this in their example Colabs, here's my version:

```
with open('data/wikisql/model/checkpoint', 'w') as f:
  f.write('model_checkpoint_path: "model.ckpt-0"')
for suffix in ['.data-00000-of-00001', '.index', '.meta']:
  shutil.copyfile(f'data/wikisql/model/model.ckpt{suffix}', f'data/wikisql/model/model.ckpt-0{suffix}')
```

Another thing, when wikiSQL unpacks into the data/ folder, point every task script to it as follows:

```
!python tapas/tapas/run_task_main.py \
  --task="WIKISQL" \
  --input_dir="data/" \
  --output_dir="data/" \
  --bert_config_file="data/wikisql/model/bert_config.json" \
  --bert_vocab_file="data/wikisql/model/vocab.txt" \
  --use_tpu="True"\
  --mode="create_data"

```
and

```
!python tapas/tapas/run_task_main.py \
  --task="WIKISQL" \
  --output_dir="data/" \
  --bert_config_file="data/wikisql/model/bert_config.json" \
  --bert_vocab_file="data/wikisql/model/vocab.txt" \
  --use_tpu="true" \
  --mode="predict_and_evaluate"

```

Note that I moved my TAPAS model/ folder to the data/wikisql/model/ folder. If you don't get the structure correct right away, the errors are actually quite useful. The above predict_and_evaluate ran for me (didn't finish though, but it got further than it had before) before my Colab crashed.

Good luck!

**Comment by alxblandin** [comment]
@aminfardi You seem to not use the train task. Have you obtained the good evaluation results?

**Comment by aminfardi** [comment]
@alxblandin mine's getting stuck here on predict_evaluate, not sure if it's just a long calculation process:

```
INFO:tensorflow:Done calling model_fn.
I1006 19:48:04.204233 140375104935808 estimator.py:1171] Done calling model_fn.
INFO:tensorflow:Graph was finalized.
I1006 19:48:04.459540 140375104935808 monitored_session.py:246] Graph was finalized.
INFO:tensorflow:Restoring parameters from data/wikisql/model/model.ckpt-0
I1006 19:48:04.461314 140375104935808 saver.py:1293] Restoring parameters from data/wikisql/model/model.ckpt-0
INFO:tensorflow:Running local_init_op.
I1006 19:48:04.821681 140375104935808 session_manager.py:505] Running local_init_op.
INFO:tensorflow:Done running local_init_op.
I1006 19:48:04.835279 140375104935808 session_manager.py:508] Done running local_init_op.
```

**Comment by alxblandin** [comment]
> @alxblandin mine's getting stuck here on predict_evaluate, not sure if it's just a long calculation process:
> 
> ```
> INFO:tensorflow:Done calling model_fn.
> I1006 19:48:04.204233 140375104935808 estimator.py:1171] Done calling model_fn.
> INFO:tensorflow:Graph was finalized.
> I1006 19:48:04.459540 140375104935808 monitored_session.py:246] Graph was finalized.
> INFO:tensorflow:Restoring parameters from data/wikisql/model/model.ckpt-0
> I1006 19:48:04.461314 140375104935808 saver.py:1293] Restoring parameters from data/wikisql/model/model.ckpt-0
> INFO:tensorflow:Running local_init_op.
> I1006 19:48:04.821681 140375104935808 session_manager.py:505] Running local_init_op.
> INFO:tensorflow:Done running local_init_op.
> I1006 19:48:04.835279 140375104935808 session_manager.py:508] Done running local_init_op.
> ```

same...for the moment :)

**Comment by aminfardi** [comment]
@alxblandin same here, somethings not setup properly still.

**Comment by aminfardi** [comment]
@alxblandin, managed to find this little snippet in the middle of all the dumps after 3.5 hours:

```
I1006 22:51:43.239191 140375104935808 calc_metrics_utils.py:414] denotation_accuracy=0.004988
dev denotation accuracy: 0.0050
I1006 22:51:43.456792 140375104935808 run_task_main.py:152] dev denotation accuracy: 0.0050
I1006 22:52:38.437489 140375104935808 calc_metrics_utils.py:414] denotation_accuracy=0.006361
test denotation accuracy: 0.0064
I1006 22:52:38.888067 140375104935808 run_task_main.py:152] test denotation accuracy: 0.0064
```

This was me running WIKISQL task. [This](https://github.com/google-research/tapas/issues/65) issue seems to get better results when switching to WIKISQL_SUPERVISED, but I'm looking for weakly supervised, so not sure how to run that.

**Comment by alxblandin** [comment]
@aminfardi Do you have changed all the references to data/wikisql into data/wikisql_supervised ? The interne programmas seem to create new folders named as the task.

On my side I got this :

> I1007 03:22:14.187629 27124 session_manager.py:505] Running local_init_op.
INFO:tensorflow:Done running local_init_op.
I1007 03:22:14.227522 27124 session_manager.py:508] Done running local_init_op.
I1007 04:56:39.790200 27124 prediction_utils.py:242] Removing padded example: EMPTY-0_0

look closely on the time_code and you will see I am having a nice evening... It started at 21:16 and it is the 3rd loop like this (21:16 ; 00:20; 3:22; 4:56;) How many times did you get the same output when you say :

> Update: it's spitting out the same output every hour on the hour.

**Comment by alxblandin** [comment]
@aminfardi 
UPDATE : After like 15hours I finnaly got 

> I1007 12:23:44.787618 27124 calc_metrics_utils.py:414] denotation_accuracy=0.783992
dev denotation accuracy: 0.7840
I1007 12:23:44.907384 27124 run_task_main.py:152] dev denotation accuracy: 0.7840
I1007 12:24:23.267191 27124 calc_metrics_utils.py:414] denotation_accuracy=0.771256
test denotation accuracy: 0.7713

Slightly good but still not the expected results... I will let it run for the rest of the day, hoping one of the dumps will led to better results. Hope yours will be good too :)

**Comment by aminfardi** [comment]
@alxblandin looking back at my output, I had the initial test results in an hour, but the next set took 3 hours to generate and it did not improve. I don't see why it should either because predict_evaluate is not retraining correct?

You're right about generating a new create_data for the supervised. Are your results for supervised? 

Regarding TPU, I had issues getting it to use TPU so I just ran it on CPU (though I am using Pro, so maybe that's why I had better runtimes). I'm going to try to get TPU going today.

**Comment by aminfardi** [comment]
@alxblandin did you have any luck replicating the reported accuracies? I could not get the weakly supervised to work, and for the supervised I'm getting the following:

```
`tf.data.TFRecordDataset(path)`
I1010 04:55:43.283555 140631071238016 calc_metrics_utils.py:414] denotation_accuracy=0.749673
dev denotation accuracy: 0.7497
I1010 04:55:43.428153 140631071238016 run_task_main.py:152] dev denotation accuracy: 0.7497
I1010 04:56:35.534448 140631071238016 calc_metrics_utils.py:414] denotation_accuracy=0.736554
test denotation accuracy: 0.7366
I1010 04:56:35.813148 140631071238016 run_task_main.py:152] test denotation accuracy: 0.7366
```

**Comment by alxblandin** [comment]
@aminfardi Hmmm...I wonder why both of us couldn't reach the paper results...

**Comment by alxblandin** [comment]
relaunched the programm with a GPU, and I got : 

> I1010 19:54:54.946234 139878567663424 prediction_utils.py:242] Removing padded example: EMPTY-0_0
INFO:tensorflow:prediction_loop marked as finished
I1010 19:54:54.983446 139878567663424 error_handling.py:115] prediction_loop marked as finished
INFO:tensorflow:prediction_loop marked as finished
I1010 19:54:54.983620 139878567663424 error_handling.py:115] prediction_loop marked as finished
I1010 19:55:13.081252 139878567663424 calc_metrics_utils.py:414] denotation_accuracy=0.783992
dev denotation accuracy: 0.7840
I1010 19:55:13.215795 139878567663424 run_task_main.py:152] dev denotation accuracy: 0.7840
I1010 19:55:46.918902 139878567663424 calc_metrics_utils.py:414] denotation_accuracy=0.771256
test denotation accuracy: 0.7713
I1010 19:55:47.187877 139878567663424 run_task_main.py:152] test denotation accuracy: 0.7713
INFO:tensorflow:Calling model_fn.
I1010 19:55:47.409703 139878567663424 estimator.py:1169] Calling model_fn.
INFO:tensorflow:Running infer on CPU/GPU
I1010 19:55:47.409882 139878567663424 tpu_estimator.py:3171] Running infer on CPU/GPU
INFO:tensorflow:*** Features ***
I1010 19:55:47.410077 139878567663424 tapas_classifier_model.py:903] *** Features ***
INFO:tensorflow:  name = aggregation_function_id, shape = (?, 1)
I1010 19:55:47.410168 139878567663424 tapas_classifier_model.py:905]   name = aggregation_function_id, shape = (?, 1)

**Comment by aminfardi** [comment]
@alxblandin what kind of runtimes did you get on GPU? I managed to get TPU going and my runs were very quick, but still nowhere near the reported accuracies. Unsure if this has to do with the "correction" they did to the WikiSQL test set prior to reporting them.

**Comment by alxblandin** [comment]
@aminfardi instead of 1h30 or 3h as in CPU I got few minutes on GPU

**Comment by alxblandin** [comment]
@aminfardi What do you get with a TPU?

**Comment by aminfardi** [comment]
@alxblandin very similar. I'm trying with the SQA dataset now to see what kind of numbers I get.

**Comment by alxblandin** [comment]
@aminfardi Does it stop for you? Mine keeps running after giving results...I thought it was to converge for better results but they are exactly the same...

**Comment by aminfardi** [comment]
@alxblandin no mine keeps running as well. I think you have to set loop_predict to false; haven't tried to address that to be honest.

**Comment by alxblandin** [comment]
@aminfardi With the parameter '--noloop_predic' I got:

> I1010 22:04:50.609548 140317586302784 calc_metrics_utils.py:414] denotation_accuracy=0.783992
dev denotation accuracy: 0.7840
I1010 22:04:50.741800 140317586302784 run_task_main.py:152] dev denotation accuracy: 0.7840
I1010 22:05:25.542444 140317586302784 calc_metrics_utils.py:414] denotation_accuracy=0.771256
test denotation accuracy: 0.7713
I1010 22:05:25.816824 140317586302784 run_task_main.py:152] test denotation accuracy: 0.7713
Evaluation finished after training step 0.
I1010 22:05:25.990206 140317586302784 run_task_main.py:152] Evaluation finished after training step 0.

**Comment by aminfardi** [comment]
@alxblandin my results for the model SQA large with reset:

```
`tf.data.TFRecordDataset(path)`
I1010 20:09:07.906886 140455312893824 calc_metrics_utils.py:414] denotation_accuracy=0.642384
dev denotation accuracy: 0.6424
I1010 20:09:07.963802 140455312893824 run_task_main.py:152] dev denotation accuracy: 0.6424
Warning: Can't evaluate for dev_seq because gs://gs-colab-bucket/data_sqa/sqa/model/random-split-1-dev_sequence.tsv doesn't exist.
W1010 20:09:08.073601 140455312893824 run_task_main.py:157] Can't evaluate for dev_seq because gs://gs-colab-bucket/data_sqa/sqa/model/random-split-1-dev_sequence.tsv doesn't exist.
I1010 20:09:19.454148 140455312893824 calc_metrics_utils.py:414] denotation_accuracy=0.652722
test denotation accuracy: 0.6527
I1010 20:09:19.531948 140455312893824 run_task_main.py:152] test denotation accuracy: 0.6527
```

About 5% lower than reported.

**Comment by aminfardi** [comment]
@alxblandin let's move the conversation [here ](https://github.com/google-research/tapas/issues/75) since we have diverged quite a bit.
