### ISSUE TITLE
❓ Pretraining Details

### ISSUE THREAD

**Issue by volker42maru** [google-research/tapas#77]
Hi there,

I have several questions regarding pre-training of TAPAS:
1. _max_position_embeddings_: Set to *1024* for TAPAS. However, the original BERT models used *512*. In the paper you state that you initialize your model from a text pre-trained BERT model. Does that mean you (1) don't initialize the position embedding, (2) copy the position embedding vector two times, (3) initialize the remaining embeddings randomly, or (4) use a custom pre-trained BERT model with `max_position_embddeddings=1024`

2. _max_seq_length_: Set to *128* in the pre-training example in the _README_. In the paper you state two different numbers. Just wanted to make sure, which _max_seq_length_ was used in the end:

   > For pre-training to be efficient, we restrict our word piece sequence length to a certain budget (e.g., we use 128 in our final experiments)

   > We run both pre-training and fine-tuning on a setup of 32 Cloud TPU v3 cores with maximum sequence length 512. 

3. Pre-training/fine-tuning: e.g. for the model `tapas_wtq_wikisql_sqa_masklm_large.zip`. I understand that the model was trained on all datasets and it was pre-trained with MLM objective on the collected wiki tables corpus. Does that mean for SQA and WikiSQL the model was fine-tuned on those tasks or also trained with MLM objective on those datasets?

I would greatly appreciate your feedback on the questions above. 

Thanks so much in advance
Volker

**Comment by thomasmueller-google** [comment]
1. We use the official Bert checkpoint but discard the position embedding table. This happens [here](https://github.com/google-research/tapas/blob/master/tapas/models/tapas_pretraining_model.py#L165).

2. We pre-train with *max_seq_length* 128 and fine-tune with 512.

3. This particular model is not described in the paper. 
    We basically train a chain:
      1. MaskLM pre-training on the pretraining data
      2. Fine-Tune model on SQA
      3. Fine-Tune model on (Supervised) WikiSQL
      4. Fine Tune model on (Weakly-Supervised) WTQ

**Comment by alxblandin** [comment]
Trying fine_tuning on Wiki_SQL supervised i got an OOM (out of memory) error

> tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[10,12,512,512] and type float on /job:localhost/replica:
         [[{{node bert/encoder/layer_6/attention/self/Softmax}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOpti

         [[loss/add_4/_5157]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOpti

  (1) Resource exhausted: OOM when allocating tensor with shape[10,12,512,512] and type float on /job:localhost/replica:
         [[{{node bert/encoder/layer_6/attention/self/Softmax}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOpti

0 successful operations.
0 derived errors ignored.

So I tried to change the _maxseq_length_  (putin it at 256 or 128) to ease the allocation and I got

> 
  (0) Invalid argument: Key: input_ids.  Can't parse serialized Example.
         [[{{node ParseSingleExample/ParseExample/ParseExampleV2}}]]
         [[IteratorGetNext]]
         [[IteratorGetNext/_5085]]
  (1) Invalid argument: Key: input_ids.  Can't parse serialized Example.
         [[{{node ParseSingleExample/ParseExample/ParseExampleV2}}]]
         [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored.

So is 512 the only valid value? Is there on other parameter to change to ease the allocution? Here is the entore command :
>     command = str('python tapas/tapas/run_task_main.py '+
    '--task="WIKISQL_SUPERVISED" '+
    '--output_dir="results" '+
    '--model_dir="tapas_sqa_inter_masklm_base" '+
    '--init_checkpoint="tapas_sqa_inter_masklm_base/model.ckpt" '+
    '--bert_config_file="tapas_sqa_inter_masklm_base/bert_config.json" '+
    '--mode="train" '+
    '--iterations_per_loop=5 '+
    '--train_batch_size=10 '+
    '--max_seq_length=512')
    os.system(command)

**Comment by muelletm** [comment]
You should be able to train models with shorter sequence lengths.

One caveat is that the TF examples have to correspond, that is, when you change the sequence length you need to regnerate the TF examples with the new sequence length.

**Comment by alxblandin** [comment]
@muelletm 
as I understand your answer I should create data like this : 

> python3 tapas/run_task_main.py \
  --task="WIKISQL_SUPERVISED" \
  --input_dir="WIKISQL\data"
  --output_dir="results" \
  --bert_vocab_file="tapas_sqa_inter_masklm_base/vocab.txt" \
  --max_seq_length = 256 \
  --mode="create_data"

Am I right?
