### ISSUE TITLE
Possible Error in TABFACT Colab Notebook Code 

### ISSUE THREAD

**Issue by ankugupt** [google-research/tapas#79]
Hi, 
I was going through your colab( [this](https://colab.research.google.com/github/google-research/tapas/blob/master/notebooks/tabfact_predictions.ipynb) ) notebook on recently released TABFACT classification but for all the examples and tables I could try the results were "REFUTE with 100% accuracy" even when my sentence was correct. I tried looking for any error but couldn't find one. Could you please check for any errors? 

Thanks 

Edit: Just now changed the model to _tapas_tabfact_inter_masklm_large_reset_ from _tapas_tabfact_inter_masklm_medium_ in the notebook and now it's now working fine. Please check the tapas_tabfact_inter_masklm_medium checkpoint.

**Comment by thomasmueller-google** [comment]
Thanks!

There was a bug in the colab where we didn't use the model with the correct options.
That should be fixed now.
We also updated the example.

**Comment by thomasmueller-google** [comment]
Closing for now, feel free to reopen.
