### ISSUE TITLE
Questions about the version of Tensorflow

### ISSUE THREAD

**Issue by Beary-wei** [google-research/tapas#94]
Hello, I have a question about the version of tensorflow. When I was fine-tuning on my tasks, I found that my devices are equipped with tensorflow 2.0.0. Is it possible to change some parts of TAPAS codes and run them in this version? Many thanks!

**Comment by thomasmueller-google** [comment]
Honestly, we are not sure.
It would be great if you could try and report your findings here!
Happy to help with any errors you find along the way.

**Comment by eisenjulian** [comment]
Just to clarify the code runs on the latest version of TensorFlow 2, but it's using the tf.compat.v1 symbol and disabling eager execution. However most of the code should be compatible with tf2 a well, especially from `tapas_classifier_model.py`, but we haven't tested it. I am closing this for now, and let us know if you find specific problems and we can try to change the code to make it more future proof.
